In [2]:
import pandas as pd

In [3]:
from sklearn.datasets import load_iris

bunch = load_iris(as_frame=True)

iris = bunch.frame.rename(columns={
    "sepal length (cm)": "sepal_length",
    "sepal width (cm)":  "sepal_width",
    "petal length (cm)": "petal_length",
    "petal width (cm)":  "petal_width",
})

iris["species"] = iris["target"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

iris = iris.drop(columns="target")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
iris["petal_length"].mean()
iris["petal_length"] < iris["petal_length"].mean()
iris[iris["petal_length"] < iris["petal_length"].mean()]

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
5            5.4          3.9           1.7          0.4      setosa
6            4.6          3.4           1.4          0.3      setosa
7            5.0          3.4           1.5          0.2      setosa
8            4.4          2.9           1.4          0.2      setosa
9            4.9          3.1           1.5          0.1      setosa
10           5.4          3.7           1.5          0.2      setosa
11           4.8          3.4           1.6          0.2      setosa
12           4.8          3.0           1.4          0.1      setosa
13           4.3          3.0           1.1          0.1      setosa
14           5.8          4.0           1.2          0.2      setosa
15           5.7          4.4           1.5          0.4      setosa
16           5.4          3.9           1.3          0.4      setosa
17           5.1          3.5           1.4          0.3      setosa
18           5.7          3.8           1.7          0.3      setosa
19           5.1          3.8           1.5          0.3      setosa
20           5.4          3.4           1.7          0.2      setosa
21           5.1          3.7           1.5          0.4      setosa
22           4.6          3.6           1.0          0.2      setosa
23           5.1          3.3           1.7          0.5      setosa
24           4.8          3.4           1.9          0.2      setosa
25           5.0          3.0           1.6          0.2      setosa
26           5.0          3.4           1.6          0.4      setosa
27           5.2          3.5           1.5          0.2      setosa
28           5.2          3.4           1.4          0.2      setosa
29           4.7          3.2           1.6          0.2      setosa
30           4.8          3.1           1.6          0.2      setosa
31           5.4          3.4           1.5          0.4      setosa
32           5.2          4.1           1.5          0.1      setosa
33           5.5          4.2           1.4          0.2      setosa
34           4.9          3.1           1.5          0.2      setosa
35           5.0          3.2           1.2          0.2      setosa
36           5.5          3.5           1.3          0.2      setosa
37           4.9          3.6           1.4          0.1      setosa
38           4.4          3.0           1.3          0.2      setosa
39           5.1          3.4           1.5          0.2      setosa
40           5.0          3.5           1.3          0.3      setosa
41           4.5          2.3           1.3          0.3      setosa
42           4.4          3.2           1.3          0.2      setosa
43           5.0          3.5           1.6          0.6      setosa
44           5.1          3.8           1.9          0.4      setosa
45           4.8          3.0           1.4          0.3      setosa
46           5.1          3.8           1.6          0.2      setosa
47           4.6          3.2           1.4          0.2      setosa
48           5.3          3.7           1.5          0.2      setosa
49           5.0          3.3           1.4          0.2      setosa
57           4.9          2.4           3.3          1.0  versicolor
60           5.0          2.0           3.5          1.0  versicolor
64           5.6          2.9           3.6          1.3  versicolor
79           5.7          2.6           3.5          1.0  versicolor
81           5.5          2.4           3.7          1.0  versicolor
93           5.0          2.3           3.3          1.0  versicolor
98           5.1          2.5           3.0          1.1  versicolor

In [5]:
a = iris[iris["petal_length"] > iris["petal_length"].mean()][["species", "petal_length"]]
print(a)
len(a)

        species  petal_length
50   versicolor           4.7
51   versicolor           4.5
52   versicolor           4.9
53   versicolor           4.0
54   versicolor           4.6
..          ...           ...
145   virginica           5.2
146   virginica           5.0
147   virginica           5.2
148   virginica           5.4
149   virginica           5.1

[93 rows x 2 columns]

93

In [6]:
iris["is_big"] = (iris["petal_length"] * iris ["petal_width"]) > 10 
iris["is_big"].value_counts()

is_big
False    117
True      33
Name: count, dtype: int64

In [7]:
b= iris.groupby("species").mean()

print(b)

print(b["sepal_length"].idxmax())

            sepal_length  sepal_width  petal_length  petal_width  is_big
species
setosa             5.006        3.428         1.462        0.246    0.00
versicolor         5.936        2.770         4.260        1.326    0.00
virginica          6.588        2.974         5.552        2.026    0.66
virginica

In [8]:
a= pd.DataFrame({
    "height": [150, 160, None, 175, 168],
    "weight": [50, None, 65, 80, None],
    "city": ["NYC", "LA", "SF", None, "LA"],
})

a["weight"] = a["weight"].fillna(a["weight"].median())
print(a["weight"].isna().sum())

0

In [9]:
from sklearn.model_selection import train_test_split

feature_cols = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

X = iris[feature_cols].to_numpy()

y = iris["species"].astype("category").cat.codes.to_numpy()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)